name: Synchronize Bazel registry
on:
  push:
    branches:
      - main

jobs:
  sync-registry:
    runs-on: 460nm-base-alpine
    steps:
      - uses: 460nm/actions/checkout@v3
      - name: Write private key
        run: echo "${{ secrets.PRIVATE_KEY }}" > key && chmod 600 ./key
      - name: Synchronize registry
        run: rsync -rvz --delete --chmod=ugo=rwX -e 'ssh -p ${{ secrets.SSH_PORT }} -i ./key -o StrictHostKeyChecking=no' ./modules/ www-write@stevenlr.com:${{ secrets.MODULES_PATH }}
